version: '3'
services:
    postgres:
        image: 'postgres:latest'
    redis: 
        image: 'redis:latest'    
    server: 
        build: 
            Dockerfile.dev
            context: ./server
    volumes:
        - /app/node_modules
        - ./server:/app        